### ISSUE TITLE
Syntax error in configure

### ISSUE THREAD

**Issue by ESP2866** [bondhugula/pet-for-pluto#1]
Hi
when building pluto I got a syntaxerror in pet/configure in line 17173 for an unknown token "ISL"
For my self I "fixed" it by commenting out the line.
Hope this is helpful

**Comment by bondhugula** [comment]
Could you please paste the complete error and attach your config.log? Also are you using the git version? commit id?

**Comment by bondhugula** [comment]
Also, please post any error build Pluto on Pluto's github issues page.

**Comment by pal-stdr** [comment]
> Also, please post any error build Pluto on Pluto's github issues page.

Hi @bondhugula 

I have found this following error while building pluto. And same error while I was trying  to build pet-for-pluto separately.

[error: /usr/include/c++/9/bits/stl_tree.h:785:8: error: static assertion failed: comparison object must be invocable as const](https://github.com/bondhugula/pluto/issues/99)

I would be really grateful, if you kindly have a look at this issue.

Thanks in advance!

**Comment by bondhugula** [comment]
> > Also, please post any error build Pluto on Pluto's github issues page.
> 
> Hi @bondhugula
> 
> I have found this following error while building pluto. And same error while I was trying to build pet-for-pluto separately.
> 
> [error: /usr/include/c++/9/bits/stl_tree.h:785:8: error: static assertion failed: comparison object must be invocable as const](https://github.com/bondhugula/pluto/issues/99)
> 
> I would be really grateful, if you kindly have a look at this issue.
> 
> Thanks in advance!

Can you report which version of Clang/LLVM is being used to build pet? Please create a new issue if it's unrelated to the original post here.

**Comment by bondhugula** [comment]
Also, please follow the updated instructions here to build pluto with all of this: https://github.com/bondhugula/pluto/blob/master/README.md

**Comment by pal-stdr** [comment]
> > > Also, please post any error build Pluto on Pluto's github issues page.
> > 
> > 
> > Hi @bondhugula
> > I have found this following error while building pluto. And same error while I was trying to build pet-for-pluto separately.
> > [error: /usr/include/c++/9/bits/stl_tree.h:785:8: error: static assertion failed: comparison object must be invocable as const](https://github.com/bondhugula/pluto/issues/99)
> > I would be really grateful, if you kindly have a look at this issue.
> > Thanks in advance!
> 
> Can you report which version of Clang/LLVM is being used to build pet? Please create a new issue if it's unrelated to the original post here.

Sorry, for posting in wrong place. The actual issue post is [here](https://github.com/bondhugula/pluto/issues/99), with all the details (which clang, ubuntu versions, etc..).

**Comment by bondhugula** [comment]
https://github.com/bondhugula/pluto/issues/99 is resolved.
